/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_my_app_testNative */

#ifndef _Included_com_my_app_testNative
#define _Included_com_my_app_testNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_my_app_testNative
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_my_app_testNative_hello
  (JNIEnv *, jclass);

/*
 * Class:     com_my_app_testNative
 * Method:    greeting
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_my_app_testNative_greeting
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
